package jogo.logica;

public enum Situacao{
    MENU_INFORMATIVO,
    ESCOLHE_JOGO,
    PRIMEIRO_A_JOGAR,
    AGUARDA_JOGADA_HUMANA,
    AGUARDA_JOGADA_VIRTUAL,
    QUER_MINIJOGO,
    MINIJOGO_CONTAS,
    MINIJOGO_PALAVRAS,
    DECISAO_PECA_ESPECIAL,
    FIM_JOGO;
}
